### ISSUE TITLE
Please update cities

### ISSUE THREAD

**Issue by PabloGirol** [Tarasa24/SCS_RPC2#3]
I would like to get the cities updated to the latest version as of now, driving on spain, portugal or other newer countries defaults to the nearest position, In my case Toulouse (FR)

**Comment by Tarasa24** [comment]
Hello, thanks for the issue. There is currently no bandwidth for this project but this should be easy enough for anyone willing to contribute. For which I can point you to general direction:
- To fetch the coordinates I've used https://github.com/Koenvh1/ETS2-City-Coordinate-Retriever
- And then simply format the output to into `cities_ets2.h` and `cities_ats.h` (word of caution, y and z coordinates in the source files are for whatever reason switched - I frankly have no idea why I did it that way two years ago lol)

**Comment by PabloGirol** [comment]
I've tried to do that, but either seems to not be working or a different language is causing it to fail, I'll give it a second try later
